### ISSUE TITLE
Getting the same values on each loop run `normal` method

### ISSUE THREAD

**Issue by Dschee** [ealdent/simple-random#5]
Here's some code I have in one of my specs:
``` ruby
10.times do
  sr = SimpleRandom.new
  rdm_num = sr.normal(25, 45).to_i
  puts "rdm_num: #{rdm_num}"
end
```

Unfortunately this leads to an output like so:
```
rdm_num: 43
rdm_num: 43
rdm_num: 43
rdm_num: 43
rdm_num: 43
rdm_num: 43
rdm_num: 43
rdm_num: 43
rdm_num: 43
rdm_num: 43
```

This isn't really a random number. So I tried to debug it with byebug – but when I check the value with byebug then it's not always 43 like it is when I run the specs using rspec without debugging.

Strange issue here, I'm gonna try to find what's causing it. Maybe someone knows what I'm doing wrong or has a suggestion, but currently it feels like this is a bug to me. Any ideas?

**Comment by Dschee** [comment]
Okay, now I refactored the code to initialize an instance of SimpleRandom only once like so:

``` ruby
sr = SimpleRandom.new
10.times do
  rdm_num = sr.normal(25, 45).to_i
  puts "rdm_num: #{rdm_num}"
end
```

Now it's working. That's strange behavior but I'm happy again. :)

**Comment by ealdent** [comment]
By default, it uses the same starting seed for the MWC algorithm.  My original use case was being able to repeat experiments so the (probably) more practical default behavior of always generating a new seed wasn't in my thoughts.  I'm open to other thoughts on that.

**Comment by Dschee** [comment]
Okay, I get it. But please document stuff like that so no one gets confused. The headline states this is a "random numbers generator" and therefore I was expecting all numbers to always be random.

You can keep the current behavior if you like but it should be clearly documented and there should be clear instructions on how to use this as a "real" random generator. I can imagine that we just add a new method that will always lead to a different number even when initializing and giving the same parameters like in my above example.

That's my opinion on this, what do you think?

**Comment by ealdent** [comment]
I documented the fact that the seed should be set if you don't want repeat runs to be identical.  Thanks for the heads up and help improving the docs!

**Comment by Dschee** [comment]
:+1:
